apiVersion: v1
kind: Service
metadata:
  name: sdc-elasticsearch
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
    role: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: api
    - port: 9300
      name: transport-protocol
  selector:
    app: sysdigcloud
    role: elasticsearch
---    
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sdc-elasticsearch 
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
spec:
  serviceName: sdc-elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: sysdigcloud
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: elasticsearch
    spec:
      initContainers:
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
        - name: elasticsearch
          image: yofti/elasticsearch:5.5.3
          securityContext:
            capabilities:
              add:
                - IPC_LOCK  
                - SYS_RESOURCE  
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          env:
            - name: ELASTICSEARCH_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.service
            - name: ELASTICSEARCH_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.cluster.name
            - name: ELASTICSEARCH_MINIMUM_MASTER_NODES
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.minimum.master.nodes                                             
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.jvm.options
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: aws-io1
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi

