---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-elasticsearch
  labels:
    app: sysdigcloud
    component: elasticsearch
    role: elasticsearch
spec:
  serviceName: sysdigcloud-elasticsearch
  podManagementPolicy: "Parallel"
  # The number of replicas needs to be passed to the pods by ensuring that the value of ELASTICSEARCH_GOSSIP_NODES_NUM
  # matches the number set here.
  replicas: 3
  template:
    metadata:
      labels:
        app: sysdigcloud
        component: elasticsearch
        role: elasticsearch
    spec:
      #affinity:
        #podAntiAffinity:
          #requiredDuringSchedulingIgnoredDuringExecution:
          #- labelSelector:
              #matchExpressions:
              #- key: app
                #operator: In
                #values:
                #- sysdigcloud
              #- key: role
                #operator: In
                #values:
                #- elasticsearch
            #topologyKey: "kubernetes.io/hostname"
      containers:
      - name: elasticsearch
        image: quay.io/sysdig/elasticsearch:5.6.14.9-sg-alpine
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 2000m
          requests:
            cpu: 500m
        env:
        - name: ELASTICSEARCH_SERVICE
          value: sysdigcloud-elasticsearch
          # This value needs to match the number of replicas specified for the statefulset. It will be used to calculate
          # The value of the -Ediscovery.zen.minimum_master_nodes parameter. To override this calculation and set this
          # parameter manually use the DISCOVERY_ZEN_MINIMUM_MASTER_NODES variable.
        - name: ELASTICSEARCH_GOSSIP_NODES_NUM
          value: "3"
        - name: ELASTICSEARCH_CLUSTER_NAME
          value: sysdigcloud
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: sysdigcloud-config
              key: elasticsearch.jvm.options
        - name: ELASTICSEARCH_USER
          valueFrom:
            configMapKeyRef:
              name: sysdigcloud-config
              key: elasticsearch.user
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticseach-password-secret
              key: password
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /usr/share/elasticsearch
          name: data
        - mountPath: /tmp/elasticsearch-certs/
          name: tool-cert
      imagePullSecrets:
      - name: sysdigcloud-pull-secret
      volumes:
      - name: tool-cert
        secret:
          secretName: ca-certs
          defaultMode: 256
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
      storageClassName: gp2 