apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-cassandra
  labels:
    app: sysdigcloud
    role: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cql
    - port: 7000
      name: intra-node-communication
    - port: 7001
      name: tls-intra-node-communication
  selector:
    app: sysdigcloud
    role: cassandra
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-cassandra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: cassandra
    spec:
      containers:
        - image: quay.io/sysdig/cassandra:2.1
          name: cassandra
          env:
            - name: CASSANDRA_SERVICE
              value: sysdigcloud-cassandra
            - name: CASSANDRA_NUM_SEEDS
              value: "2"
            - name: CASSANDRA_CLUSTER_NAME
              value: sysdigcloud
            - name: JVM_EXTRA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.jvm.options
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      volumes:
        - name: data
          emptyDir: {}