apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysdigcloud-kafka
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: sysdigcloud
      role: kafka
  serviceName: sysdigcloud-kafka
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - kafka
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: HOSTNAME_COMMAND
          value: "hostname"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE_CLIENT:PLAINTEXT,OUTSIDE_CLIENT:PLAINTEXT,REPLICATION:PLAINTEXT
        - name: KAFKA_LISTENERS 
          value: INSIDE_CLIENT://:9092,OUTSIDE_CLIENT://:9093,REPLICATION://:9094
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: REPLICATION
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE_CLIENT://_{HOSTNAME_COMMAND}.sysdigcloud-kafka:9092,REPLICATION://_{HOSTNAME_COMMAND}.sysdigcloud-kafka:9094
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: sysdigcloud-zookeeper:2181
        - name: BROKER_ID_COMMAND
          value: hostname | awk -F'-' '{print $3}'
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "60000"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "60000"
        image: wurstmeister/kafka:2.11-2.0.0
        imagePullPolicy: IfNotPresent
        name: broker
        ports:
        - containerPort: 9092
          protocol: TCP
        - containerPort: 9093
          protocol: TCP
        - containerPort: 9094
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - echo "" | nc -w 1 127.0.0.1 9092
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kafka
          name: data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: sysdigcloud-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        emptyDir: {}
  updateStrategy:
    type: OnDelete
