apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-zookeeper
  labels:
    app: sysdigcloud
    role: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: sysdigcloud
    role: zookeeper
  sessionAffinity: None
