apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-cassandra-1 # Cassandra node number
spec:
  replicas: 1
  template:
    metadata:
      labels:
        instance: "1" # Cassandra node number
        app: sysdigcloud
        role: cassandra
    spec:
      containers:
        - image: quay.io/sysdig/cassandra:2.1
          name: cassandra
          env:
            - name: CASSANDRA_SERVICE
              value: sysdigcloud-cassandra
            - name: CASSANDRA_NUM_SEEDS
              value: "2"
            - name: CASSANDRA_CLUSTER_NAME
              value: sysdigcloud
            - name: JVM_EXTRA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.jvm.options
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      volumes:
        # Uncomment this for emptyDir volumes
        - name: data
          emptyDir: {}
        # Uncomment this for GCE Disk
        # - name: data
        #   gcePersistentDisk:
        #     pdName: <volume-name>
        #     fsType: ext4
        # Uncomment this for AWS EBS
        # - name: data
        #   awsElasticBlockStore:
        #     volumeID: <volume-id>
        #     fsType: ext4
