---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sdc-worker
  namespace: sysdigcloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: worker
    spec:
      containers:
        - name: worker
          image: quay.io/sysdig/sysdigcloud-backend:858
          volumeMounts:
            - name: logs
              mountPath: /var/log/sysdigcloud
            - name: config
              mountPath: /opt/kubernets_config
            - name: ssl
              mountPath: /opt/certs/
          resources:
            requests:
              cpu: 1000m
              memory: 3Gi
            limits:
              cpu: 3000m
              memory: 6Gi
          env:
            - name: ROLES
              value: worker
            - name: LOG_ROLE
              value: worker
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: api.url
            - name: JVM_EXTRA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: sysdigcloud.jvm.worker.options
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 2
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      volumes:
        - name: logs
        - name: config
          configMap:
            name: sysdigcloud-config
        - name: ssl
          secret:
            secretName: sysdigcloud-ssl-secret
