apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pull-secret.yaml
  - storage-class.yaml
  - lb-config.yaml
  - config.yaml
  - scanning-secrets.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: sysdigcloud-ssl-secret
  namespace: {{ .Values.namespace }}
  files:
    - tls.crt={{ .Values.sysdig.certificate.cert }}
    - tls.key={{ .Values.sysdig.certificate.key  }}
