---
# Source: pjchart/templates/ingress_controller/default-backend-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-default-backend
  namespace: sysdigcloud-pj-template
spec:
  ports:
    - port: 8080
  selector:
    run: ingress-default-backend
