sg_admin:
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - ALL
sg_readonly:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '*':
      '*':
        - READ
