---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel-stateset
spec:
  serviceName: redis-sentinel-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      containers:
      - name: redis-sentinel
        image: quay.io/sysdig/redis:3.2-v2
        imagePullPolicy: Always
        env:
        - name: SENTINEL
          value: redis-primary
        ports:
        - containerPort: 26379
          name: redis-sentinel
        resources:
          requests:
            cpu: "500m"
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 30
          timeoutSeconds: 15
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 45
          periodSeconds: 15
