---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-pri-sts
spec:
  serviceName: redis-primary-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-pri
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-pri-sts
        image: quay.io/sysdig/redis:3.2-v2
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis-pri-sts
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 30
          timeoutSeconds: 15
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 45
          periodSeconds: 15
