---
# Source: pjchart/templates/redis-stateful/redis-primary-svc-statefulset.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: sysdigcloud-pj-template
  name: redis-primary
  labels:
    app: redis-primary
spec:
  ports:
  - port: 6379
    name: redis-primary
  selector:
    app: redis-primary
