apiVersion: v1
kind: Secret
metadata:
  name: sysdigcloud-pull-secret
  namespace: sysdigcloud
data:
  .dockerconfigjson: "ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjM2x6WkdsbkszbHZablJwWDIxaGEyOXVibVZ1T2pWRVJrOUpPRGhPUkZoVVdFdFpSVFJRUWpsRVNUSklUalV4TVVkQlZGTklXVlF5UkVZNU9GTk1WbE5GUVRRek5GWllWVXBSVFZaWlRsRkNORmM1VkZVPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9"
type: kubernetes.io/dockerconfigjson
