---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIEAPI
  labels:
    app.kubernetes.io/managed-by: ingress-config
    app.kubernetes.io/name: ingress-config
    app.kubernetes.io/part-of: sysdigcloud
    role: ingress-config
    tier: infra
  name: sysdigcloud-api-ingress
spec:
  rules:
    - host: ae3cb4ecd57f111e9afc90a5a199fa68-757061889.us-east-1.elb.amazonaws.com
      http:
        paths:
          - backend:
              serviceName: sysdigcloud-api
              servicePort: 8080 
            path: /
  tls:
    - hosts:
        - ae3cb4ecd57f111e9afc90a5a199fa68-757061889.us-east-1.elb.amazonaws.com
      secretName: sysdigcloud-ssl-secret
