---
apiVersion: v1
kind: Service
metadata:
  name: collector-headless-service
  labels:
    app: sysdigcloud
    role: collector
spec:
  clusterIP: None
  ports:
    - port: 6443
      name: secure-collector
  selector:
    app: sysdigcloud
    role: collector
