apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-config
data:
  ## MySQL service:
  # configure here the MySQL service endpoint DNS/IP
  mysql.endpoint: sysdigcloud-mysql
  # MySQL user
  mysql.user: admin
  # MySQL password
  mysql.password: password
  ## Cassandra service:
  # configure here the Cassandra service endpoint DNS/IP
  cassandra.endpoint: sysdigcloud-cassandra
  # cassandra replication factor to use
  cassandra.replication.factor: "1"
  # Cassandra  JVM options
  cassandra.jvm.options: ""
  ## Redis service:
  # configure here the Redis service endpoint DNS/IP
  redis.endpoint: sysdigcloud-redis
  ## SMTP service:
  # SMTP server address
  smtp.server: ""
  # SMTP server port
  smtp.server.port: "25"
  # SMTP user (leave empty if your server doesn't require authentication)
  smtp.user: ""
  # SMTP password (leave empty if your server doesn't require authentication)
  smtp.password: ""
  # SMTP Secure Connection options
  smtp.tls: "false"
  smtp.ssl: "false"
  #From Header for notification
  smtp.from.address: ""
  ## Sysdig Cloud
  # configure here the collector service endpoint DNS/IP
  collector.endpoint: sysdigcloud-collector
  # collector port, if you use a NodePort service set the proper port value here
  collector.port: "6443"
  # configure here the api service http(s) URL, if you use a Nodeport service set the proper port value here
  api.url: https://sysdigcloud-api:443
  # Sysdig Cloud default console user
  sysdigcloud.default.user: test@sysdig.com
  # Sysdig Cloud default console user password
  sysdigcloud.default.user.password: test
  # Sysdig Cloud application JVM options
  sysdigcloud.application.jvm.options: ""
  # Sysdig Cloud license
  sysdigcloud.license: ""