---
apiVersion: v1
kind: Secret
metadata:
  name: sysdigcloud-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjM2x6WkdsbksyMWhjbXN1YW1GamEzTnZiam8zT0RKVlFWcEZNVE5EVUVNMFZsRlhUalpYU1RGTVJFNWFNVTVLVkVzelNUTldPVkJVVkZwUVNWYzNUamhHV0VaUk0xQkpNa3BNTmtaSU4xSktWMGhQIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
