---
apiVersion: v1
kind: Secret
metadata:
  name: sysdigcloud-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjM2x6WkdsbkszQnlZWFpwYm1wdmRHaHBibUYwYUdGdU9rOUROekUwTmtneFdsZFdNVVpZUmxaTlRrYzNOa2xWUVZSSE1VaFNRMFpOTUZoUFJUWlFSemxGT0VoRFNsSmFVelJETXpCVlZVY3dUVFZMUmxGSVJWRT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
