apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: api
    spec:
      containers:
        - name: api
          image: quay.io/sysdig/sysdigcloud-backend:494
          volumeMounts:
            - name: logs
              mountPath: /var/log/sysdigcloud
            - name: config
              mountPath: /opt/kubernets_config
            - name: ssl
              mountPath: /opt/certs/
          env:
            - name: ROLES
              value: api
            - name: LOG_ROLE
              value: api
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: api.url
            - name: JVM_EXTRA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: sysdigcloud.jvm.options
          # 
          # If you're running multiple replicas, it is advisable to configure the limits below. Limiting resources 
          # can help stabilize rolling updates later down the road.
          #

          # resources:
          #   # minimum resources for container
          #   requests:
          #     memory: "13G"
          #     cpu: "4"
          #   # maximum resources for container
          #   limits:
          #     memory: "64G"
          #     cpu: "32"

          readinessProbe:
            httpGet:
              path: /api/ping
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 2
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      volumes:
        - name: logs
        - name: config
          configMap:
            name: sysdigcloud-config
        - name: ssl
          secret:
            secretName: sysdigcloud-ssl-secret
