apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-api  
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: api        
          resources:
            limits:
              cpu: "16"
              memory: "16Gi"
            requests:
              cpu: "4"
              memory: "8Gi"
