apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysdigcloud-postgresql
spec:
  template:
    spec:
      containers:
        - name: postgresql
          resources:
            requests:
              cpu: 500m
              memory: 1Gi     
