apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysdigcloud-postgresql
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Gi
        storageClassName: {{ .Values.sysdig.storageclass.name }}
