---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      hostNetwork: true
      serviceAccountName: ingress-controller
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      containers:
      - name: haproxy-ingress
        image: quay.io/sysdig/haproxy-ingress:v0.7-beta.7
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --tcp-services-configmap=$(POD_NAMESPACE)/haproxy-tcp-services
        - --reload-strategy=reusesocket
        - --allow-cross-namespace
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          hostPort: 443
          protocol: TCP
        - name: healthcheck
          containerPort: 10253
          hostPort: 10253
          protocol: TCP
        - name: collector
          containerPort: 6443
          hostPort: 6443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10253
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10253
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
             cpu: 2
             memory: 2Gi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: rsyslog-server
        image: quay.io/sysdig/rsyslog:8.34.0-r0-20180708T0208-git-cb867ef
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: 150m
            memory: 30Mi 
          requests:
            cpu: 50m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
