apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-collector 
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: collector        
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
