kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysdig-cluster-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sysdig-account
    namespace: sysdigcloud
roleRef:
  kind: ClusterRole
  name: sysdig-cluster-role
apiGroup: rbac.authorization.k8s.io