---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysdig-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysdig-cluster-role-binding
  namespace: sysdigcloud
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sysdigcloud
roleRef:
  kind: ClusterRole
  name: sysdig-cluster-role
  apiGroup: rbac.authorization.k8s.io
