apiVersion: v1
kind: Route
metadata:
  name: collector-passthrough-ssl
spec:
  host: <COLLECTOR_HOST_NAME_MUST_BE_DIFFERENT_FROM_API_HOSTNAME>
  to:
    kind: Service
    name: sysdigcloud-collector
  tls:
    termination: passthrough
  port:
    targetPort: 6443
