---
#context: gke_sysdig-disney_us-west1-a_sysdig-disney-qa
#context: kops.yoftilabs.com
global:
  sysdigNamespace: sysdigcloud
  #sysdigcloudProvider: gcp 
  sysdigcloudProvider: aws
  sysdigPullSecret: 
  sysdigcloudLicense: 


  #Images
  sysdigBackendImage: quay.io/sysdig/sysdigcloud-backend:800
  sysdigFrontendImage: sysdig/agent:0.78.1
  sysdigCassandraImage: yofti/cassandra:2.2.11
  sysdigElasticsearchImage: yofti/elasticsearch:5.5.3
  sysdigRedisImage: yofti/redis:4.0.2
  sysdigMysqlImage: mysql:5.7
  sysdigXtrabackupImage: gcr.io/google-samples/xtrabackup:1.0

  #Replica Counts
  sysdigApiReplicaCount: 1
  sysdigWorkerReplicaCount: 1
  sysdigCollectorReplicaCount: 1
  sysdigMysqlMasterReplicaCount: 1
  sysdigMysqlSlavesReplicaCount: 2
  sysdigRedisMasterReplicaCount: 1
  sysdigRedisSlavesReplicaCount: 2
  sysdigCassandraReplicaCount: 3
  sysdigElasticsearchReplicaCount: 3



  #StorageClass defintions for GKE/GCE type pd-ssd
  #sysdigStorageclassName: gce-pd
  #sysdigStorageclassProvisioner: kubernetes.io/gce-pd
  #sysdigStorageclassType: pd-ssd

  #StorageClass defintions for AWS type io1
  sysdigStorageclassName: aws-io1
  sysdigStorageclassProvisioner: kubernetes.io/aws-ebs
  sysdigStorageclassType: io1
  sysdigStorageclassZones: us-east-1e
  sysdigStorageclassIopsPerGb: 50

  #StorageClass defintions for AWS type gp2
  #sysdigStorageclassName: aws-gp2
  #sysdigStorageclassProvisioner: kubernetes.io/aws-ebs
  #sysdigStorageclassType: gp2
  #sysdigStorageclassZones: us-east-1e

  #PVC disk sizes
  sysdigCassandraDiskSize: 30Gi
  sysdigElasticsearchDiskSize: 30Gi
  sysdigRedisDiskSize: 30Gi
  sysdigMysqlDiskSize: 30Gi

  #Backend resource allocation
  apiResourceRequestCpu: 1000m
  apiResourceRequestMemory: 3Gi
  apiResourceLimitsCpu: 2000m
  apiResourceLimitsMemory: 5Gi
  collectorResourceRequestCpu: 1000m
  collectorResourceRequestMemory: 3Gi
  collectorResourceLimitsCpu: 3000m
  collectorResourceLimitsMemory: 6Gi
  workerResourceRequestCpu: 1000m
  workerResourceRequestMemory: 3Gi
  workerResourceLimitsCpu: 3000m
  workerResourceLimitsMemory: 6Gi

  #Datastore resource allocation
  cassandraResourceRequestCpu: 1000m
  cassandraResourceRequestMemory: 2Gi
  cassandraResourceLimitsCpu: 3000m
  cassandraResourceLimitsMemory: 8Gi
  elasticsearchResourceRequestCpu: 500m
  elasticsearchResourceRequestMemory: 2Gi
  elasticsearchResourceLimitsCpu: 2000m
  elasticsearchResourceLimitsMemory: 4Gi
  mysqlResourceRequestCpu: 100m
  mysqlResourceRequestMemory: 2Gi
  mysqlResourceLimitsCpu: 2000m
  mysqlResourceLimitsMemory: 4Gi
  redisResourceRequestCpu: 500m
  redisResourceRequestMemory: 2Gi
  redisResourceLimitsCpu: 2000m
  redisResourceLimitsMemory: 4Gi

  #Application Ports
  sysdigK8sExposeMethod: LoadBalancer
  #sysdigK8sExposeMethod: NodePort
  sysdigApiExternalPort: 443
  sysdigApiTargetPort: 443
  sysdigCollectorExternalPort: 6443
  sysdigCollectorTargetPort: 6443
  sysdigRedisExternalPort: 6379
  sysdigRedisTargetPort: 6379
  sysdigRedisGossipExternalPort: 16379
  sysdigRedisGossipInternalPort: 16379
  sysdigMySqlExternalPort: 3306
  sysdigMySqlTargetPort: 3306
  sysdigXtrabackupPort: 3307
  sysdigCassandraCqlPort: 9042
  sysdigCassandraThriftPort: 9160
  sysdigCassandraIntraNodePort: 7000
  sysdigCassandraIntraNodeTlsPort: 7001
  sysdigCassandraJmxPort: 7199
  sysdigElasticsearchApiPort: 9200
  sysdigElasticsearchTransportPort: 9300


  #servicenames
  sysdigApiServiceName: sdc-api
  sysdigCollectorServiceName: sdc-collector
  sysdigCassandraServiceName: sdc-cassandra
  sysdigElasticsearchServiceName: sdc-elasticsearch
  sysdigRedisServiceName: sdc-redis
  sysdigRedisSlaveServiceName: sdc-redis-slave
  sysdigMysqlServiceName: sdc-mysql
  sysdigMysqlSlaveServiceName: sdc-mysql-slave

include:
  - name: templates/backend/api
  - name: templates/backend/collector
  - name: templates/backend/worker
  - name: templates/frontend
  - name: templates/datastores/cassandra
  - name: templates/datastores/elasticsearch
  - name: templates/datastores/mysql/master
  - name: templates/datastores/mysql/slaves
  - name: templates/datastores/redis/master
  - name: templates/datastores/redis/slaves
  - name: templates/datastores/storageclasses/gce-pd
  - name: templates/datastores/storageclasses/aws-gp2
  - name: templates/datastores/storageclasses/aws-io1
  - name: templates/configmaps
    values:
      configmapName: sysdigcloud-config
      elasticsearchUrl: http://sdc-elasticsearch
      redisEndpoint: sdc-redis
      cassandraEndpoint: sdc-cassandra
      mysqlEndpoint: sdc-mysql
      collectorEndpoint: sdc-collector
      collectorPort: "6443"
      apiUrl: https://sdc-api:443
      #passwords
      sysdigcloudDefaultUser: test@sysdig.com
      sysdigcloudDefaultUserPassword: test
      cassandraUser: ""
      cassandraPassword: ""
      redisPassword: ""
      mysqlUser: admin
      mysqlPassword: password
      mysqlRootUser: root
      mysqlRootPassword: password
      #jvm options
      cassandraJvmOptions: -Xms2g -Xmx2g
      elasticsearchJvmOptions: -Xms2g -Xmx2g
      sysdigcloudJvmOptions: -Xms2g -Xmx2g
      #elasticsearch
      elasticsearchService: sdc-elasticsearch
      elasticsearchClusterName: sysdigcloud
      elasticsearchMinimumMasterNodes: 1
      #Cassandra
      cassandraClusterName: sysdigcloud
      cassandraService: sdc-cassandra
      cassandraSeeds: sdc-cassandra-0
      cassandraSeedProvider: io.k8s.cassandra.KubernetesSeedProvider
      #cassandraEndpointSnitch: GoogleCloudSnitch
      cassandraEndpointSnitch: Ec2Snitch
      cassandraStartRpc: "true"
      cassandraSecure: "false"
      cassandraSslEnabled: "false"
      cassandraSslCiphers: ""
      cassandraPort: "9042"
      cassandraReplicationFactor: "3"
      sysdigcloudCapturesCassandraStorage: "true"
      #smtp
      smtpServer: ""
      smtpServerPort: "25"
      smtpUser: ""
      smtpPassword: ""
      smtpTls: "false"
      smtpSsl: "false"
      smtpFromAddress: ""
      #logging
      sysdigcloudLoggingStdout: "true"
      #Auth and LDAP
      sysdigcloudRestrictPasswordLogin: "false"
      sysdigcloudOauthAllowedDomainsList: ""
      sysdigcloudGoogleOauthClientId: ""
      sysdigcloudGoogleOauthClientSecret: ""
      sysdigcloudLdapEnabled: "false"
      sysdigcloudLdapEndpoint: ""
      sysdigcloudLdapManagerDn: ""
      sysdigcloudLdapManagerPassword: ""
      sysdigcloudLdapRootDn: ""
      sysdigcloudLdapUserSearchBase: ""
      sysdigcloudLdapUserSearchFilter: ""
      sysdigcloudLdapGroupSearchBase: ""
      sysdigcloudLdapGroupSearchFilter: ""
      sysdigcloudLdapGroupMembershipFilter: ""
