---
apiVersion: v1
kind: Secret
metadata:
  name: sysdigcloud-pull-secret
  namespace: sysdigcloud
data:
  .dockerconfigjson: ""
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-config
  namespace: sysdigcloud
data:
  #License
  sysdigcloud.license: ""
  #endpoints
  elasticsearch.url: "http://sdc-elasticsearch"
  redis.endpoint: "sdc-redis"
  cassandra.endpoint: "sdc-cassandra"
  mysql.endpoint: "sdc-mysql"
  collector.endpoint: "sdc-collector"
  collector.port: "6443"
  api.url: "https://sdc-api:443"
  #passwords
  sysdigcloud.default.user: "test@example.com"
  sysdigcloud.default.user.password: "changeme"
  cassandra.user: ""
  cassandra.password: ""
  redis.password: ""
  mysql.user: "admin"
  mysql.password: "password"
  mysql.root.user: "root"
  mysql.root.password: "password"
  #jvm options
  cassandra.jvm.options: "-Xms4g -Xmx4g"
  elasticsearch.jvm.options: "-Xms2g -Xmx2g"
  sysdigcloud.jvm.api.options: "-Xms2g -Xmx5g"
  sysdigcloud.jvm.worker.options: "-Xms2g -Xmx5g"
  sysdigcloud.jvm.collector.options: "-Xms4g -Xmx8g"
  #elasticsearch
  elasticsearch.service: "sdc-elasticsearch"
  elasticsearch.cluster.name: "sysdigcloud"
  elasticsearch.minimum.master.nodes: "1"
  #Cassandra
  cassandra.cluster.name: "sysdigcloud"
  cassandra.service: "sdc-cassandra"
  cassandra.seeds: "sdc-cassandra-0.sdc-cassandra.sysdigcloud.svc.cluster.local"
  cassandra.seed.provider: "io.k8s.cassandra.KubernetesSeedProvider"
  cassandra.endpoint.snitch: "GoogleCloudSnitch"
  cassandra.start.rpc: "true"
  cassandra.secure: "false"
  cassandra.ssl.enabled: "false"
  cassandra.ssl.ciphers: ""
  cassandra.port: "9042"
  cassandra.replication.factor: "3"
  sysdigcloud.captures.cassandra.storage: "true"
  #smtp
  smtp.server: ""
  smtp.server.port: "25"
  smtp.user: ""
  smtp.password: ""
  smtp.tls: "false"
  smtp.ssl: "false"
  smtp.from.address: ""
  #logging
  sysdigcloud.logging.stdout: "true"
  #Auth and LDAP
  sysdigcloud.restrict.password.login: "false"
  sysdigcloud.oauth.allowed.domains.list: ""
  sysdigcloud.google.oauth.client.id: ""
  sysdigcloud.google.oauth.client.secret: ""
  sysdigcloud.ldap.enabled: "false"
  sysdigcloud.ldap.endpoint: ""
  sysdigcloud.ldap.manager.dn: ""
  sysdigcloud.ldap.manager.password: ""
  sysdigcloud.ldap.root.dn: ""
  sysdigcloud.ldap.user.search.base: ""
  sysdigcloud.ldap.user.search.filter: ""
  sysdigcloud.ldap.group.search.base: ""
  sysdigcloud.ldap.group.search.filter: ""
  sysdigcloud.ldap.group.membership.filter: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-mysql-config
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
data:
  master.cnf: |-
    [client]
    port   = 3306
    socket   = /var/run/mysqld/mysqld.sock
    default-character-set=utf8

    [mysql]
    default-character-set=utf8
    [mysqld_safe]
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    nice   = 0
    [mysqld]
    user   = mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    port   = 3306
    basedir    = /usr
    datadir    = /var/lib/mysql
    tmpdir   = /tmp
    lc-messages-dir  = /usr/share/mysql
    explicit_defaults_for_timestamp
    collation-server = utf8_unicode_ci
    init-connect='SET NAMES utf8'
    character-set-server = utf8
    log-error  = /var/log/mysql/error.log
    # Recommended in standard MySQL setup
    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    open_files_limit = 16384
    max_connections = 100000
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    # Replicate to slaves
    log-bin=sdc-mysql-0-bin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-mysql-config-slave
  namespace: sysdigcloud
  labels:
    app: sysdigcloud-mysql-slave
data:
  slave.cnf: |-
    [client]
    port   = 3306
    socket   = /var/run/mysqld/mysqld.sock
    default-character-set=utf8

    [mysql]
    default-character-set=utf8
    [mysqld_safe]
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    nice   = 0
    [mysqld]
    user   = mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    port   = 3306
    basedir    = /usr
    datadir    = /var/lib/mysql
    tmpdir   = /tmp
    lc-messages-dir  = /usr/share/mysql
    explicit_defaults_for_timestamp
    collation-server = utf8_unicode_ci
    init-connect='SET NAMES utf8'
    character-set-server = utf8
    log-error  = /var/log/mysql/error.log
    # Recommended in standard MySQL setup
    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    open_files_limit = 16384
    max_connections = 100000
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    # Writes from master only
    super-read-only
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-redis-config
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
    role: redis
data:
  redis.conf: |+
    tcp-backlog 65536
    maxclients 30000
    cluster-enabled no
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-redis-config-slave
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
    role: redis-slave
data:
  redis.conf: |+
    tcp-backlog 65536
    maxclients 30000
    cluster-enabled no 
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
    slave-serve-stale-data yes
    slaveof sdc-redis-0.sdc-redis 6379
