---
global:
  namespace: sysdigcloud
  provider: gcp 
  #Provider: aws
  pullSecret: ""
  license:  ""


  #Images
  backendImage: quay.io/sysdig/sysdigcloud-backend:858
  frontendImage: sysdig/agent
  cassandraImage: yofti/cassandra:2.2.11
  elasticsearchImage: yofti/elasticsearch:5.5.3
  redisImage: yofti/redis:4.0.2
  mysqlImage: mysql:5.7
  xtrabackupImage: gcr.io/google-samples/xtrabackup:1.0

  #Replica Counts
  apiReplicaCount: 1
  workerReplicaCount: 1
  collectorReplicaCount: 1
  mysqlMasterReplicaCount: 1
  mysqlSlavesReplicaCount: 2
  redisMasterReplicaCount: 1
  redisSlavesReplicaCount: 2
  cassandraReplicaCount: 3
  elasticsearchReplicaCount: 3



  #StorageClass defintions for GKE/GCE type pd-ssd
  storageclassName: gce-pd
  storageclassProvisioner: kubernetes.io/gce-pd
  storageclassType: pd-ssd

  #StorageClass defintions for AWS type io1
  #storageclassName: aws-io1
  #storageclassType: io1
  #storageclassZones: us-east-1e
  #storageclassIopsPerGb: 50

  #StorageClass defintions for AWS type gp2
  #storageclassName: aws-gp2
  #storageclassProvisioner: kubernetes.io/aws-ebs
  #storageclassType: gp2
  #storageclassZones: us-east-1e

  #PVC disk sizes
  cassandraDiskSize: 50Gi
  elasticsearchDiskSize: 10Gi
  redisDiskSize: 10Gi
  mysqlDiskSize: 10Gi

  #Backend resource allocation
  apiResourceRequestCpu: 1000m
  apiResourceRequestMemory: 3Gi
  apiResourceLimitsCpu: 2000m
  apiResourceLimitsMemory: 5Gi
  collectorResourceRequestCpu: 1000m
  collectorResourceRequestMemory: 3Gi
  collectorResourceLimitsCpu: 6000m
  collectorResourceLimitsMemory: 6Gi
  workerResourceRequestCpu: 1000m
  workerResourceRequestMemory: 3Gi
  workerResourceLimitsCpu: 3000m
  workerResourceLimitsMemory: 6Gi

  #Datastore resource allocation
  cassandraResourceRequestCpu: 1000m
  cassandraResourceRequestMemory: 4Gi
  cassandraResourceLimitsCpu: 6000m
  cassandraResourceLimitsMemory: 12Gi
  elasticsearchResourceRequestCpu: 500m
  elasticsearchResourceRequestMemory: 2Gi
  elasticsearchResourceLimitsCpu: 2000m
  elasticsearchResourceLimitsMemory: 4Gi
  mysqlResourceRequestCpu: 100m
  mysqlResourceRequestMemory: 2Gi
  mysqlResourceLimitsCpu: 2000m
  mysqlResourceLimitsMemory: 4Gi
  redisResourceRequestCpu: 500m
  redisResourceRequestMemory: 2Gi
  redisResourceLimitsCpu: 2000m
  redisResourceLimitsMemory: 4Gi

  #Application Ports
  k8sExposeMethod: LoadBalancer
  #K8sExposeMethod: NodePort
  apiExternalPort: 443
  apiTargetPort: 443
  collectorExternalPort: 6443
  collectorTargetPort: 6443
  redisExternalPort: 6379
  redisTargetPort: 6379
  redisGossipExternalPort: 16379
  redisGossipInternalPort: 16379
  mySqlExternalPort: 3306
  mySqlTargetPort: 3306
  xtrabackupPort: 3307
  cassandraCqlPort: 9042
  cassandraThriftPort: 9160
  cassandraIntraNodePort: 7000
  cassandraIntraNodeTlsPort: 7001
  cassandraJmxPort: 7199
  elasticsearchApiPort: 9200
  elasticsearchTransportPort: 9300


  #servicenames
  apiServiceName: sdc-api
  collectorServiceName: sdc-collector
  cassandraServiceName: sdc-cassandra
  elasticsearchServiceName: sdc-elasticsearch
  redisServiceName: sdc-redis
  redisSlaveServiceName: sdc-redis-slave
  mysqlServiceName: sdc-mysql
  mysqlSlaveServiceName: sdc-mysql-slave

  #frontend configuration
  collectorUrl: collector.sysdigcloud.com
  accessKey: f65322d7-da0c-44ea-b365-2506bb0db382
  agentTags: os:ubuntu-16.04,orechestrator:k8s,cloud_provider:gke,cluster:sysdig-disney,backend_version:858,owner:yofti

include:
  - name: templates/backend/api
  - name: templates/backend/collector
  - name: templates/backend/worker
  - name: templates/frontend
  - name: templates/datastores/cassandra
  - name: templates/datastores/elasticsearch
  - name: templates/datastores/mysql/master
  - name: templates/datastores/mysql/slaves
  - name: templates/datastores/redis/master
  - name: templates/datastores/redis/slaves
  - name: templates/datastores/storageclasses/gce-pd
  - name: templates/datastores/storageclasses/aws-gp2
  - name: templates/datastores/storageclasses/aws-io1
  - name: templates/configmaps
    values:
      configmapName: sysdigcloud-config
      elasticsearchUrl: http://sdc-elasticsearch
      redisEndpoint: sdc-redis
      cassandraEndpoint: sdc-cassandra
      mysqlEndpoint: sdc-mysql
      collectorEndpoint: sdc-collector
      collectorPort: "6443"
      apiUrl: https://sdc-api:443
      #passwords
      defaultUser: test@sysdig.com
      defaultUserPassword: test
      cassandraUser: ""
      cassandraPassword: ""
      redisPassword: ""
      mysqlUser: admin
      mysqlPassword: password
      mysqlRootUser: root
      mysqlRootPassword: password
      #options
      cassandraJvmOptions: -Xms2g -Xmx4g
      elasticsearchJvmOptions: -Xms2g -Xmx2g
      jvmOptions: -Xms2g -Xmx4g -Xmn1g
      #elasticsearch
      elasticsearchService: sdc-elasticsearch
      elasticsearchClusterName: sysdigcloud
      elasticsearchMinimumMasterNodes: 1
      #Cassandra
      cassandraClusterName: sysdigcloud
      cassandraService: sdc-cassandra
      cassandraSeeds: sdc-cassandra-0
      cassandraSeedProvider: io.k8s.cassandra.KubernetesSeedProvider
      cassandraEndpointSnitch: GoogleCloudSnitch
      #cassandraEndpointSnitch: Ec2Snitch
      cassandraStartRpc: "true"
      cassandraSecure: "false"
      cassandraSslEnabled: "false"
      cassandraSslCiphers: ""
      cassandraPort: "9042"
      cassandraReplicationFactor: "3"
      capturesCassandraStorage: "true"
      #smtp
      smtpServer: ""
      smtpServerPort: "25"
      smtpUser: ""
      smtpPassword: ""
      smtpTls: "false"
      smtpSsl: "false"
      smtpFromAddress: ""
      #logging
      loggingStdout: "true"
      #Auth and LDAP
      restrictPasswordLogin: "false"
      oauthAllowedDomainsList: ""
      googleOauthClientId: ""
      googleOauthClientSecret: ""
      ldapEnabled: "false"
      ldapEndpoint: ""
      ldapManagerDn: ""
      ldapManagerPassword: ""
      ldapRootDn: ""
      ldapUserSearchBase: ""
      ldapUserSearchFilter: ""
      ldapGroupSearchBase: ""
      ldapGroupSearchFilter: ""
      ldapGroupMembershipFilter: ""
