---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-cassandra
spec:
  serviceName: cassandra-service
  replicas: 5
  selector:
    matchLabels:
      app: sysdigcloud
      role: cassandra
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: cassandra
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sysdigcloud
              - key: role
                operator: In
                values:
                - cassandra
            topologyKey: "kubernetes.io/hostname"
      containers:
        - image: quay.io/sysdig/cassandra:2.1.20.5
          name: cassandra
          env:
            - name: CASSANDRA_SERVICE
              value: sysdigcloud-cassandra
            - name: CASSANDRA_NUM_SEEDS
              value: "2"
            - name: CASSANDRA_CLUSTER_NAME
              value: sysdigcloud
            # If not using CASSANDRA_SERVICE discovery, manually configure the seeds
            # - name: CASSANDRA_SEEDS
            #   value: ""
            # If using multiple directories for data, set the path list
            # - name: CASSANDRA_DATA_DIRS
            #   value: "/var/lib/cassandra/data /var/lib/cassandra/data2"
            - name: JVM_EXTRA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.jvm.options
            - name: CASSANDRA_SECURE
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.secure
            - name: CASSANDRA_SSL
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.ssl.enabled
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: "16G"
              cpu: "8"
            limits:
              memory: "16G"
              cpu: "8"
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - 'if [[ $(nodetool status | grep ${POD_IP}) == *"UN"* ]]; then exit 0; else exit 1; fi'
            initialDelaySeconds: 15
            failureThreshold: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: data
      volumes:
        - hostPath:
            path: /mnt/nvme/cassandra-data-volume
            type: ""
          name: data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      nodeSelector:
        kops.k8s.io/instancegroup: storage-nodes
